### ISSUE TITLE
multiple .jshintrc seems to be not supported. 

### ISSUE THREAD

**Issue by cyrilcoutelier** [FGRibreau/check-build#27]
My project is defined as described bellow : 
 - .checkbuild
 - .jshintrc
 - src/
 - tests/
    - .jshintrc
    - specs/

Here is the content of .checkbuild : 
```json
  "jshint": {
    "args": [
      "src/**/*.js",
      "tests/specs/**/*.js",
      "tests/utils/**/*.js"
    ]
  },
```

My problem is that when launching check-build, it seems that jshint does not use the "test" .jshintrc when checking the test files : all the "it", "before", "describe" raise warnings while there is `"mocha": true,` inside the .jshintrc. 
When I launch jshint manually it is working fine. 
I used jshint v2.8.0 for the manual test, and check-build v1.5.0. 

I assume that check-build only look to the project root for the .jshintrc file.

**Comment by FGRibreau** [comment]
> I assume that check-build only look to the project root for the .jshintrc file.

Indeed, that's what it does and that's what we want (it's a good tradeoff). If you need special treatment for specific files use the "/* jshint" comment notation :)
