### ISSUE TITLE
David output is blank (deps are not checked)

### ISSUE THREAD

**Issue by valeriansaliou** [FGRibreau/check-build#37]
Looks like David check task is buggy. With a standard check-build configuration, the task is executed w/o checking or outputting anything (no dependencies up to date message).

If I manually downgrade a random dependency, David still does not complaint that dependencies are out-to-date.

Would that be a bug introduced recently, or a misconfiguration on my side? - I remember it used to work on older projects I had, like 4 months ago.

Here's my .checkbuild conf file:

```json
{
  "checkbuild": {
    "enable": ["jshint", "jscs", "nsp", "david"],
    "continueOnError": true,
    "allowFailures": false
  },
  "jshint": {
    "args": ["src/**/*.js"]
  },
  "jscs": {
    "args": ["src/**/*.js"]
  },
  "nsp": {}
}
```

Note that other tasks are successfully applied (JSHint fails/validates as expected, etc).

Cheers!

**Comment by FGRibreau** [comment]
Hello @valeriansaliou,

I tested it and it worked even without any `david:{}` configuration object. Do you have check-build last version? **1.7.1** ?

To verify:

```shell
node -e "console.log(require('`npm bin -g`/../lib/node_modules/check-build/package.json').version);"
```

**Comment by valeriansaliou** [comment]
Yep, 1.7.1 is being used.

```bash
➜  ~  node -e "console.log(require('`npm bin -g`/../lib/node_modules/check-build/package.json').version);"
1.7.1
```

Though, I'm not using check-build from global context but rather from local (package) context.
It is defined as a devDependency as:

```json
"devDependencies": {
  "check-build": "^1.7.1"
}
```

**Comment by FGRibreau** [comment]
hum, I don't see what could go wrong... I added some debug in [v2.0.0](https://github.com/FGRibreau/check-build/blob/master/CHANGELOG.md#v200-2015-08-07) and refactored a little the internals.

```shell
npm install check-build@latest -S && DEBUG=* `npm bin`/check-build
```

**Comment by valeriansaliou** [comment]
@FGRibreau okay, got some more insight for you there: https://infinit.io/_/7h9eWGe

When I execute david separately from its bare binary file, it "succeeds" at failing on outdated deps.

**Comment by valeriansaliou** [comment]
Oh crap! Got it.

Looks like your default configuration doesn't check for devDependencies by default, although david binary defaults does.

Got a proper return w/ the following david options in .checkbuild:

``json
{
  "david": {"dev":true,"stable":true,"ignore":[]}
}
```

Anyway, should be specified in the README or anywhere else, can submit a MR if you'd like.

**Comment by FGRibreau** [comment]
Fixed in https://github.com/FGRibreau/check-build/commit/cf049436ecccf1e4dda3ec9087c099977b4c16de, closing :)
