### ISSUE TITLE
Current status of this project

### ISSUE THREAD

**Issue by DanielRuf** [FGRibreau/check-build#74]
Hi, what is the status of this project? Is it still maintained?

**Comment by FGRibreau** [comment]
It is yes :)
Do you wish to add/improve something ?

**Comment by DanielRuf** [comment]
Well, there are 8 open PRs and the last change on master was 2 years ago (outdated deos).

**Comment by DanielRuf** [comment]
Well, there are 8 open PRs and the last change on master was 2 years ago (outdated deps).
